workflow: nextstrain

# All HBV genes
genes: ["P", "S", "C", "X"]

# Reference sequence 
reference:
  id: NC_003977
  genbank: ../ingest/defaults/NC_003977.gb
  gff: "defaults/NC_003977.2_version_2026.gff"

auspice:
  auspice_config: "defaults/auspice_config_nextstrain.json"
  color_by_metadata:
    - "HBV Type"
    - "HBV Subtype"
    - region
    - country
    - division
    - date

#__________________________________________________________________________________________________________ FILTERING CRITERIA __________________________________________________________________________________________________________

sampling:
  augur_custom_filter: 'year > "1977" & (is_lab_host != True) & host == "Homo sapiens"'  # First sequenced genome is 1978, not sure if the earlier ones are old samples and relieable
  group_by:
    - region
    - year

# Defines whether we filter by sequence completeness (length) and which thresholds to use. DO NOT use small genes in ancestr^al reconstruction if length filtering is not strict.
length_filtering:
  use_as_filter: true   
  min_length: 3000
  max_length: 3400

# Defines whether only sequenes with a known subgenotype will be sampled for the phylogeny and nextclade dataset
subgenotype_filtering_fulltree: true
subgenotype_filtering_singleclade: false


# all branches with length higher than this threshold will be pruned from the tree
long_branch_threshold:  0.25  # 0.3
tip_branch_threshold: 0.1  #0.1 # 0.1 works for pretty clean tree to still see some recent recombinants. 

filter_genbank_vs_nextclade: true


# There are 2 ways to filter messy subgenotype annotation so that trees appear cleaner:
# 1) Clade Purity: Broadly enforce minimal purity of subclades of a given size (clade fraction), i.e. delete small impurities/supposed outliers 
# 2) Clade Settings: Different ways to deal with monophyletic groups of given subtype smaller than a minimum size (either delete labels, annotations or prune them completely)

clade_purity:
  use_as_filter: false
  clade_fraction: 0.3 # Multiplied by genotype tree size gives the clade size where purity is enforced
  minimal_monophyletic_purity: 0.1 # Minimum fraction of sequences that need to belong to same subtype in a clade to not be removed

clade_settings:
  only_monophyletic: true # if true, only clades that are monophyletic with respect to the genotype annotation will be considered as clades (this leads to multiple clades per subtype), If false, MRCAs of genotypes are considered as clades (even if containing outliers)
  min_count_per_clade: 10
  min_count_per_subclade: 5
  min_count_mode: "use_for_pruning" # chose from ["use_for_branch_display", "use_for_annotation","use_for_pruning"]  -> monophyletic clades of any subtype of size <min_count are either just not displayed with branch-labels, annotated as "other", or pruned completely from the tree
  branch_display_only_largest: false # if only_monophyletic is true: branch labels for non-monophyletic subtypes are per default (False) displayed for ALL monophyletic clades of a subtype. Change to True to display labels ONCE only for the largest monophyletic clade.
#________________________________________________________________________________________________________________________________________________________________________________________________________________________________________


# n is number of sequences to use (build-specific), Development mode defines supplementary targets, dev_n is number of sequences per build to use in dev mode
n_totaltree: 3000
n_stitched_parts: 800
dev: true
dev_n_ingest: 300
dev_n_totaltree: 100
dev_n_stitched_parts: 50

# Defines which exact transcript to use for the acestral reconstruction,
gene_products_for_ancestral:
  S: "envL"                    #can be either: "envL", "envM" or "envS"
  C: "pre-capsid"              #can be either: "pre-capsid" or "capsid"
ancestral_genes: # If length filtering is disabled or not strict, ancestral reconstruction might not work for all genes, as some sequences might be too short. Perform ancestral reconstruction for longer genes (P > S> C > X).
  prod: ["P", "S", "C", "X"]
  dev: ["X"] #Testing reconstruction on 1 gene speeds runtime up significantly 

# Defines which genes to use for the phylogenetic reconstruction. Ideally P or S with lowest recombination burden (Note that ancestral reconstruction will be performed for all genes) 
gene_mask: ["P"]








#__________________________________________________________________________________________________________ TARGETS / BUILDS __________________________________________________________________________________________________________

# Defines which genotypes to include in the single build phylogeny
#single_build_genotypes: ["A","B","C","D","F", "I"]
single_build_genotypes: ["A", "B", "C", "D", "E", "F", "G", "H", "I"]

# TODO FOR SOME STRAINS ALL SEQUENCES GET FILTERED, and check if problem is somewhere else potentially
all_genotypes: ["A", "B", "C", "D", "E", "F", "G", "H", "I"]
#all_genotypes: ["A", "B", "C", "D", "E"]