# All HBV genes
genes: ["P", "S", "C", "X"]

# Reference sequence 
reference:
  id: NC_003977
  genbank: ../ingest/defaults/NC_003977.gb
  gff: "defaults/NC_003977.2_version_2026.gff"

#__________________________________________________________________________________________________________ FILTERING CRITERIA __________________________________________________________________________________________________________
# Defines whether we filter by sequence completeness (length) and which thresholds to use. DO NOT use small genes in ancestr^al reconstruction if length filtering is not strict.
length_filtering:
  use_as_filter: false   
  min_length: 3000
  max_length: 3400

# Defines whether only sequenes with a known subgenotype will be sampled for the phylogeny and nextclade dataset
subgenotype_filtering: true


# all branches with length higher than this threshold will be pruned from the tree
long_branch_threshold:  0.25  # 0.3
tip_branch_threshold: 0.01  #0.1 # 0.1 works for pretty clean tree to still see some recent recombinants. 

filter_genbank_vs_nextclade: true

clade_purity:
  use_as_filter: true
  clade_fraction: 0.3
  minimal_monophyletic_purity: 0.1
#________________________________________________________________________________________________________________________________________________________________________________________________________________________________________


# Development mode defines supplementary targets, dev_n is number of sequences per build to use in dev mode
dev: false
dev_n: 500

# Defines which exact transcript to use for the acestral reconstruction,
gene_products_for_ancestral:
  S: "envL"                    #can be either: "envL", "envM" or "envS"
  C: "pre-capsid"              #can be either: "pre-capsid" or "capsid"
ancestral_genes: ["P"] #["P", "S", "C", "X"]  # If length filtering is disabled or not strict, ancestral reconstruction might not work for all genes, as some sequences might be too short. Perform ancestral reconstruction for longer genes (P > S> C > X).

# Defines which genes to use for the phylogenetic reconstruction. Ideally P or S with lowest recombination burden (Note that ancestral reconstruction will be performed for all genes) 
#gene_mask: ["S","P"]
gene_mask: ["P"]




clade_settings:
  min_count_per_clade: 20
  min_count_per_subclade: 8
  branch_display_mode: "display_once" # chose from ["display_once", "display_all", "manually_curated"]



#__________________________________________________________________________________________________________ TARGETS / BUILDS __________________________________________________________________________________________________________

# Defines which genotypes to include in the single build phylogeny
#single_build_genotypes: ["A","B","C","D","F", "I"]
single_build_genotypes: ["A", "B", "C", "D", "E", "F", "G", "H", "I"]

# TODO FOR SOME STRAINS ALL SEQUENCES GET FILTERED, and check if problem is somewhere else potentially
all_genotypes: ["A", "B", "C", "D", "E", "F", "G", "H", "I"]
#all_genotypes: ["A", "B", "C", "D", "E"]