# This configuration file should contain all required configuration parameters
# for the ingest workflow to run to completion.

# Used to re-circularise genomes. This should be the same as the reference in the nextclade dataset!
# Also force-included for a number of datasets
reference_accession: "NC_003977"
reference_genbank: "defaults/NC_003977.gb"

entrez_query: 'Hepatitis+B+virus[All+Fields]complete+genome[All+Fields]'

# Path to the nextclade dataset, which will be used to align all sequences
nextclade_dataset: "../nextclade_datasets/references/NC_003977/versions/2023-08-22"

# technically CDSs, but we use these terms rather interchangeably.
# These should be the entire list of CDSs in the nextclade dataset's genemap
genes: ['envS', 'envM', 'envL', 'X', 'pre-capsid', 'capsid', 'pol']
