
#    Expcted inputs from ingest:
#        sequences="../ingest/results/sequences.fasta",
#        metadata="../ingest/results/metadata.tsv",
#        alignment="../ingest/results/aligned.fasta",

#if config file not defined else snakemake --configfile
configfile: "defaults/config.yaml"

GENE_MASKS = config["gene_mask"]
MODES = ["basic", "stitched", "single-clade"]
ALL_GTS = config["all_genotypes"]
SINGLE_BUILD_GENOTYPES = config["single_build_genotypes"]

STITCHED_DIR = "results/stitched/{gene}_global"

full_tree_targets = (
    expand("auspice_datasets/{gene}_masked/full-tree.json", gene=GENE_MASKS)
    if config.get("dev", False)
    else []
)

include: "rules/filter_and_masking.smk"



rule all: 
    input: 
        main_clades   = expand("auspice_datasets/{gene}_masked/main-clades.json", gene=GENE_MASKS),
        single_clades = expand("auspice_datasets/{gene}_masked/clade_{key}.json", gene=GENE_MASKS, key=SINGLE_BUILD_GENOTYPES),
        full_tree     = full_tree_targets




# Reference sequence is to be included in the alignment but excluded from tree building to avoid it appearing in wrong individual clade-trees.
rule augur_tree:
    input:
        alignment = "results/{mode}/{key}/{gene}_masked/{gene}_masked_aln.fasta",
    output:
        tree      = "results/{mode}/{key}/{gene}_masked/{gene}_masked.tree.nwk",
    threads: 4
    shell:
        """
        augur tree \
          --alignment {input.alignment} \
          --method fasttree \
          --output {output.tree}
        """


# TO DO: Pruned nodes are written to exclude files that could be used in future runs directly. This is not implemented yet however. 
rule prune_tree:
    input:
        tree_nwk="results/{mode}/{key}/{gene}_masked/{gene}_masked.tree.nwk",
        metadata="results/{mode}/{key}/filtered.tsv",
        script="scripts/prune_trees.py"
    output:
        out_tree="results/{mode}/{key}/{gene}_masked/{gene}_masked.pruned.tree.nwk",
        metadata="results/{mode}/{key}/{gene}_masked/{gene}_metadata.pruned.tsv",
        exclude= "results/{mode}/{key}/{gene}_masked/{gene}_exclude.txt",
    params:
        long_branch_threshold = config["long_branch_threshold"],
        tip_branch_threshold  = config["tip_branch_threshold"],
        metadata_col="subgenotype_genbank", # for clade purity filtering,

        purity_args=(
            f"--purity_metadata_col subgenotype_genbank "
            f"--minimal_monophyletic_purity {config['clade_purity']['minimal_monophyletic_purity']} "
            f"--maximal_monophyletic_fraction {config['clade_purity']['clade_fraction']}"
            if config["clade_purity"]["use_as_filter"] else ""
        ),

        minclade_args=(
            f"--minclade_metadata_cols genotype_genbank subgenotype_genbank "
            f"--prune_min_counts {config['clade_settings']['min_count_per_clade']} {config['clade_settings']['min_count_per_subclade']}"
            if config["clade_settings"]["min_count_mode"] == "use_for_pruning" else ""
        ),
    shell:
        r"""
        python {input.script} \
          --tree {input.tree_nwk} \
          --metadata_in {input.metadata} \
          --metadata_out {output.metadata} \
          --cutoff_allbranches {params.long_branch_threshold} \
          --cutoff_tips {params.tip_branch_threshold} \
          --out_tree {output.out_tree} \
          --exclude {output.exclude} \
          {params.purity_args} \
          {params.minclade_args}     
        
        n=$(tr ' ' '\n' < {output.exclude} | sed '/^$/d' | sort -u | wc -l)
        echo "$n unique accessions in {output.exclude}"
        """       



rule augur_refine:
    input:
        tree      = "results/{mode}/{key}/{gene}_masked/{gene}_masked.pruned.tree.nwk",
        alignment = "results/{mode}/{key}/{gene}_masked/{gene}_masked_aln.fasta"
    output:
        tree      = "results/{mode}/{key}/{gene}_masked/{gene}_masked_refined.tree.nwk",
    threads: 4
    shell:
        """
        augur refine \
          --tree {input.tree} \
          --alignment {input.alignment} \
          --root mid_point \
          --output-tree {output.tree}
        """


# NOTE THAT THIS MAPPING INCLUDES PRE-REGIONS IN C AND S 
rule alias_translations_for_augur:
    input:
        dir="../ingest/data/nextclade",
        pol="../ingest/data/nextclade/cds_pol.fasta",
    params: # for genes with muultiple transcripts 
        s=config["gene_products_for_ancestral"]["S"], # "envL", "envM" or "envS"
        c=config["gene_products_for_ancestral"]["C"], # "pre-capsid" or "capsid"
    output:
        p="../ingest/data/nextclade/cds_P.fasta", # maybe make those temp files...
        s="../ingest/data/nextclade/cds_S.fasta",
        c="../ingest/data/nextclade/cds_C.fasta"
    shell:
        r"""
        cp {input.pol} {output.p}
        cp {input.dir}/cds_{params.s}.fasta {output.s}
        cp {input.dir}/cds_{params.c}.fasta {output.c}
        """


# TODO take ref sequence as root here for reconstruction as well?
rule ancestral:
    input:
        tree=     "results/{mode}/{key}/{gene}_masked/{gene}_masked_refined.tree.nwk",
        alignment="results/{mode}/{key}/filtered.fasta", # Using non-masked alignment for ancestral reconstruction
        annotation= config["reference"]["gff"],
        translations=expand("../ingest/data/nextclade/cds_{g}.fasta", g=config["genes"]),
        root = "../nextclade_datasets/references/NC_003977/versions/2023-08-22/reference.fasta",   # Mutations are relative to the reference sequence
 
    output:
        node_data = "results/{mode}/{key}/{gene}_masked/ancestral/{gene}.json",
        sequences = "results/{mode}/{key}/{gene}_masked/ancestral/{gene}.fasta",
    params: 
        genes=" ".join(config["ancestral_genes"]),
        translation_pattern="../ingest/data/nextclade/cds_%GENE.fasta",

    threads: 4
    shell:
        r"""
        augur ancestral \
          --tree {input.tree} \
          --alignment {input.alignment} \
          --annotation {input.annotation} \
          --genes {params.genes} \
          --translations {params.translation_pattern} \
          --output-node-data {output.node_data} \
          --output-sequences {output.sequences} \
          --root-sequence {input.root}

        """



#______________________________________________________________________________________________________________________________________________________________________________________________
# Rules for stitching together trees from different genotypes into a single tree 
#______________________________________________________________________________________________________________________________________________________________________________________________

rule collect_trees_for_stitching:
    input:
        trees=lambda wc: expand(
            "results/stitched/{g}/{gene}_masked/{gene}_masked_refined.tree.nwk",
            g=ALL_GTS, gene=[wc.gene]
        ),
        alns=lambda wc: expand(
            "results/stitched/{g}/{gene}_masked/{gene}_masked_aln.fasta",
            g=ALL_GTS, gene=[wc.gene]
        ),
    output:
        trees_dir=directory("results/stitched/{gene}_global/trees"),
        aln_dir=directory("results/stitched/{gene}_global/aln"),
        touch="results/stitched/{gene}_global/collect.done",
    params:
        g_list=" ".join(ALL_GTS)
    shell:
        r"""
        mkdir -p {output.trees_dir} {output.aln_dir}

        for g in {params.g_list}; do
            cp "results/stitched/$g/{wildcards.gene}_masked/{wildcards.gene}_masked_refined.tree.nwk" "{output.trees_dir}/$g.nwk"
            cp "results/stitched/$g/{wildcards.gene}_masked/{wildcards.gene}_masked_aln.fasta" "{output.aln_dir}/$g.fasta"
        done

        touch {output.touch}
        """

rule group_trees:
    input:
        done="results/stitched/{gene}_global/collect.done"
    output:
        stitched_tree="results/stitched/{gene}_global/tree_raw.nwk",
    params:
        trees="results/stitched/{gene}_global/trees",
        aln=  "results/stitched/{gene}_global/aln",
        outdir=directory("results/stitched/{gene}_global"),
        ref_id = config["reference"]["id"]
    shell:
        r"""
        python3 scripts/make_global_tree.py \
          --tree-dir {params.trees} \
          --alignment-dir {params.aln} \
          --output {output.stitched_tree} \
          --outdir {params.outdir} \
          --ref-id {params.ref_id}
        """


rule refine_stitched:
    input:
        tree = STITCHED_DIR + "/tree_raw.nwk",
        metadata="data/filtered/metadata.len_filtered.tsv",
    output:
        tree = STITCHED_DIR + "/{gene}_tree.nwk",
        node_data = STITCHED_DIR + "/node_data/{gene}_branch_lengths.json",
    shell:
        r"""
        augur refine --tree {input.tree} --metadata {input.metadata} \
                     --keep-root \
                     --output-tree {output.tree} --output-node-data {output.node_data}
        """



rule clades_stitched:
    input:
        tree = STITCHED_DIR + "/{gene}_tree.nwk",
        metadata = "data/filtered/metadata.len_filtered.tsv",
        script = "scripts/assign_clades.py"   
    output:
        clades = STITCHED_DIR + "/{gene}_clades.json",
    params:
         min_count = config["clade_settings"]["min_count_per_clade"],
         min_count_mode = config["clade_settings"]["min_count_mode"],
         only_monophyletic_flag = "--only_monophyletic" if config["clade_settings"].get("only_monophyletic", True) else "" ,        
         branch_display_flag = "--branch_display_only_largest" if config["clade_settings"].get("branch_display_only_largest",False) else "",
         genotype_col = "genotype_genbank",
         nextclade_label = "HBV Type",
    shell:
        r"""        
        python3 {input.script} \
          --tree {input.tree} \
          --metadata {input.metadata} \
          --output {output.clades} \
          --min-count {params.min_count} \
          --min-count-mode {params.min_count_mode} \
          --subtype-col {params.genotype_col} \
          --nextclade-label "{params.nextclade_label}" \
          {params.only_monophyletic_flag} \
          {params.branch_display_flag}       
         """

rule sub_clades_stitched:
    input:
        tree = STITCHED_DIR + "/{gene}_tree.nwk",
        metadata = "data/filtered/metadata.len_filtered.tsv",
        fallback_clades = STITCHED_DIR + "/{gene}_clades.json", 
        script = "scripts/assign_clades.py"
    output:
        clades = STITCHED_DIR + "/{gene}_subclades.json",
    params:
         min_count = config["clade_settings"]["min_count_per_subclade"],
         min_count_mode = config["clade_settings"]["min_count_mode"],
         only_monophyletic_flag = "--only_monophyletic" if config["clade_settings"].get("only_monophyletic", True) else "" ,        
         branch_display_flag = "--branch_display_only_largest" if config["clade_settings"].get("branch_display_only_largest",False) else "",
         genotype_col = "subgenotype_genbank",
         fallback_genotype_col = "genotype_genbank", # in case subgenotype information is missing, use genotype information to assign to major clade
         nextclade_label = "HBV Subtype",
         fallback_annotation_nextclade_label = "HBV Type", # if subtype information is missing and genotype information is used as fallback, use the major clade as annotation for nextclade clades as well
    shell:
        r"""        
        python3 {input.script} \
          --tree {input.tree} \
          --metadata {input.metadata} \
          --output {output.clades} \
          --min-count {params.min_count} \
          --min-count-mode {params.min_count_mode} \
          --subtype-col {params.genotype_col} \
          --nextclade-label "{params.nextclade_label}" \
          --fallback-genotype-col {params.fallback_genotype_col} \
          --fallback-annotation-file {input.fallback_clades} \
          --fallback-annotation-nextclade-label "{params.fallback_annotation_nextclade_label}" \
          {params.only_monophyletic_flag} \
          {params.branch_display_flag}
        """

    


rule ancestral_stitched:
    input:
        tree = STITCHED_DIR + "/{gene}_tree.nwk",
        aln=expand("results/stitched/{key}/filtered.fasta", key=ALL_GTS), # Using non-masked alignments for ancestral reconstruction
        annotation= config["reference"]["gff"],
        translations=expand("../ingest/data/nextclade/cds_{g}.fasta", g=config["genes"]), 
        root = "../nextclade_datasets/references/NC_003977/versions/2023-08-22/reference.fasta",   # Mutations are relative to the reference sequence

    output:
        node_data = STITCHED_DIR + "/node_data/{gene}_muts.json",
    params:
        genes=" ".join(config["ancestral_genes"]),
        translation_pattern="../ingest/data/nextclade/cds_%GENE.fasta",
        outdir="results/stitched/{gene}_global",
        ref_id= config["reference"]["id"],
 
    shell:
        r"""
        set -euo pipefail

        outdir="{params.outdir}"
        # mkdir -p "$outdir"

        combined="$outdir/combined_nonmasked_aln.fasta"

        awk -v ref="{params.ref_id}" '
        /^>/ {{
            is_ref = ($0 == ">" ref) 
            if (is_ref && seen_ref) skip=1
            else {{
                skip=0
                if (is_ref) seen_ref=1
            }}
        }}
        !skip {{ print }}
        ' {input.aln} > "$combined"

        augur ancestral --tree {input.tree} --alignment "$combined" \
                        --translations {params.translation_pattern} --genes {params.genes} \
                        --output-node-data {output.node_data} \
                        --annotation {input.annotation}  \
                        --root-sequence {input.root} 
        """


#rule add_metadata_stitched:
#    input:
#        tree = STITCHED_DIR + "/{gene}_tree.nwk",
#        metadata = "data/filtered/metadata.len_filtered.tsv",
#    output:
#        node_metadata = STITCHED_DIR + "/{gene}_node_metadata.json",
#    run:
#        metadata = pd.read_csv(input.metadata, sep="\t", index_col="strain").to_dict(orient="index")
#        T = Phylo.read(input.tree, "newick")
#        nodes = {}
#        for node in T.get_terminals():
#            m = metadata.get(node.name, {})
#            nodes[node.name] = {
#                "country": m.get("country"),
#                "date": m.get("date"),
#                "LANL_subtype": m.get("subtype"),
#                "Strain_name": m.get("name"),
#            }
#        with open(output.node_metadata[0], "w") as f:
#            json.dump({"nodes": nodes}, f)


rule export_stitched:
    wildcard_constraints:
        gene="P|S|C|X"  
    input:
        tree = STITCHED_DIR + "/{gene}_tree.nwk",
        metadata = "data/filtered/metadata.len_filtered.tsv",
        config = "defaults/auspice_config.json",
        node_data = [
            STITCHED_DIR + "/node_data/{gene}_branch_lengths.json",
            STITCHED_DIR + "/node_data/{gene}_muts.json",
            STITCHED_DIR + "/{gene}_subclades.json",
            STITCHED_DIR + "/{gene}_clades.json",]
            #STITCHED_DIR + "/{gene}_node_metadata.json",
        
    output:
        auspice_json = STITCHED_DIR + "/{gene}.json",
    threads: 1
    shell:
        """
        augur export v2 \
            --tree "{input.tree}" \
            --node-data {input.node_data} \
            --metadata "{input.metadata}" \
            --metadata-id-columns accession \
            --output "{output.auspice_json}" \
            --auspice-config "{input.config}" \
            --color-by-metadata \
                "HBV Type" \
                "HBV Subtype" \
                region \
                country \
                division \
                date \
            --minify-json \
            --include-root-sequence-inline
        """


#______________________________________________________________________________________________________________________________________________________________________________________________


rule create_auspice_view_main_clades:
    input:
        main_clades="results/stitched/{gene}_global/{gene}.json",
    output:
        main_clades="auspice_datasets/{gene}_masked/main-clades.json",
    wildcard_constraints:
        gene="|".join(config["gene_mask"]),
    shell:
        r"""
        cp {input.main_clades} {output.main_clades}
        """


rule create_auspice_view_full_tree:
    input:
        full_tree="results/basic/all/{gene}_masked/{gene}.json",
    output:
        full_tree="auspice_datasets/{gene}_masked/full-tree.json",
    wildcard_constraints:
        gene="|".join(config["gene_mask"]),
    shell:
        r"""
        cp {input.full_tree} {output.full_tree}
        """


# rule create_auspice_view_full_tree:
#     input: 
#         main_clades="results/stitched/{gene}_global/{gene}.json",
#         full_tree="results/basic/all/{gene}_masked/{gene}.json",
#     output:
#         main_clades="auspice_datasets/{gene}_masked/main-clades.json",
#         full_tree="auspice_datasets/{gene}_masked/full-tree.json",
#     wildcard_constraints:
#         gene="|".join(config["gene_mask"]),
#     shell:
#         r"""
#         # mkdir -p auspice_datasets/{wildcards.gene}_masked
#         cp {input.main_clades} {output.main_clades}
#         cp {input.full_tree} {output.full_tree}
#         """

rule create_auspice_view_single:
    input:
        json="results/single-clade/{key}/{gene}_masked/{gene}.json"
    output:
        single_clades="auspice_datasets/{gene}_masked/clade_{key}.json",
    wildcard_constraints:
        gene="|".join(config["gene_mask"]),
        key="|".join(SINGLE_BUILD_GENOTYPES),
    shell:
        r"""
        # mkdir -p auspice_datasets/{wildcards.gene}_masked
        cp {input.json} {output.single_clades}
        """








#______________________________________________________________________________________________________________________________________________________________________________________________

# rule find_new_clades:
#     input:
#         tree="results/stitched/{gene}_global/{gene}.json",
#         metadata="data/filtered/metadata.len_filtered.tsv",
#     output:
#         clade_summary="results/{gene}_masked_stitched_clade_summary.tsv",
#     params:
#         #target="A",
#         genotype_cols="genotype_genbank subgenotype_genbank", 
#         id_col="accession",
#         min_purity=0.9,
#         min_child_purity=0.5,
#     shell:
#         r"""
#         python scripts/find_majority_clade.py \
#             --tree {input.tree} \
#             --metadata {input.metadata} \
#             --genotype-col {params.genotype_cols} \
#             --id-col {params.id_col} \
#             --min-purity {params.min_purity} \
#             --child-min-purity {params.min_child_purity} \
#             --output {output.clade_summary}
#         """





rule clades_per_build:
    input:
        tree = "results/{mode}/{key}/{gene}_masked/{gene}_masked_refined.tree.nwk",
        metadata = "data/filtered/metadata.len_filtered.tsv",
        script = "scripts/assign_clades.py"
    output:
        clades = "results/{mode}/{key}/{gene}_masked/{gene}_clades.json"
    params:
        min_count = config["clade_settings"]["min_count_per_clade"],
        min_count_mode = config["clade_settings"]["min_count_mode"],
        only_monophyletic_flag = "--only_monophyletic" if config["clade_settings"].get("only_monophyletic", True) else "",
        branch_display_flag = "--branch_display_only_largest" if config["clade_settings"].get("branch_display_only_largest", False) else "",
        genotype_col = "genotype_genbank",
        nextclade_label = "HBV Type",
    shell:
        r"""
        python3 {input.script} \
          --tree {input.tree} \
          --metadata {input.metadata} \
          --output {output.clades} \
          --min-count {params.min_count} \
          --min-count-mode {params.min_count_mode} \
          --subtype-col {params.genotype_col} \
          --nextclade-label "{params.nextclade_label}" \
          {params.only_monophyletic_flag} \
          {params.branch_display_flag}
        """


rule sub_clades_per_build:
    input:
        tree = "results/{mode}/{key}/{gene}_masked/{gene}_masked_refined.tree.nwk",
        metadata = "data/filtered/metadata.len_filtered.tsv",
        fallback_clades = "results/{mode}/{key}/{gene}_masked/{gene}_clades.json",
        script = "scripts/assign_clades.py"
    output:
        clades = "results/{mode}/{key}/{gene}_masked/{gene}_subclades.json"
    params:
        min_count = config["clade_settings"]["min_count_per_subclade"],
        min_count_mode = config["clade_settings"]["min_count_mode"],
        only_monophyletic_flag = "--only_monophyletic" if config["clade_settings"].get("only_monophyletic", True) else "",
        branch_display_flag = "--branch_display_only_largest" if config["clade_settings"].get("branch_display_only_largest", False) else "",
        genotype_col = "subgenotype_genbank",
        fallback_genotype_col = "genotype_genbank",
        nextclade_label = "HBV Subtype",
        fallback_annotation_nextclade_label = "HBV Type",
    shell:
        r"""
        python3 {input.script} \
          --tree {input.tree} \
          --metadata {input.metadata} \
          --output {output.clades} \
          --min-count {params.min_count} \
          --min-count-mode {params.min_count_mode} \
          --subtype-col {params.genotype_col} \
          --nextclade-label "{params.nextclade_label}" \
          --fallback-genotype-col {params.fallback_genotype_col} \
          --fallback-annotation-file {input.fallback_clades} \
          --fallback-annotation-nextclade-label "{params.fallback_annotation_nextclade_label}" \
          {params.only_monophyletic_flag} \
          {params.branch_display_flag}
        """
rule augur_export:
    wildcard_constraints:
        gene="P|S|C|X"
    input:
        tree = "results/{mode}/{key}/{gene}_masked/{gene}_masked_refined.tree.nwk",
        node_data = [
            "results/{mode}/{key}/{gene}_masked/ancestral/{gene}.json",
            "results/{mode}/{key}/{gene}_masked/{gene}_subclades.json",
            "results/{mode}/{key}/{gene}_masked/{gene}_clades.json",
        ],
        metadata = "results/{mode}/{key}/{gene}_masked/{gene}_metadata.pruned.tsv",
        config = "defaults/auspice_config.json",
    output:
        auspice_json = "results/{mode}/{key}/{gene}_masked/{gene}.json",
    threads: 1
    shell:
        """
        augur export v2 \
        --tree "{input.tree}" \
        --node-data {input.node_data} \
        --metadata "{input.metadata}" \
        --metadata-id-columns accession \
        --auspice-config "{input.config}" \
        --color-by-metadata \
            "HBV Type" \
            "HBV Subtype" \
            region \
            country \
            division \
            date \
        --output "{output.auspice_json}"
        """


# rule augur_export:
#     wildcard_constraints:
#         gene="P|S|C|X"  
#     input:
#         tree       ="results/{mode}/{key}/{gene}_masked/{gene}_masked_refined.tree.nwk",
#         node_data = "results/{mode}/{key}/{gene}_masked/ancestral/{gene}.json",
#         metadata   ="results/{mode}/{key}/{gene}_masked/{gene}_metadata.pruned.tsv",
#         config     ="defaults/auspice_config.json",
#     output:
#         auspice_json = "results/{mode}/{key}/{gene}_masked/{gene}.json",
#     threads: 1
#     shell:
#         """
#         augur export v2 \
#         --tree "{input.tree}" \
#         --node-data "{input.node_data}"  \
#         --metadata "{input.metadata}" \
#         --metadata-id-columns accession \
#         --auspice-config "{input.config}" \
#         --color-by-metadata \
#             "HBV Type" \
#             "HBV Subtype" \
#             genotype \
#             region \
#             country \
#             division \
#             date \
#         --output "{output.auspice_json}"
#         """