
#    Expcted inputs from ingest:
#        sequences="../ingest/results/sequences.fasta",
#        metadata="../ingest/results/metadata.tsv",
#        alignment="../ingest/results/aligned.fasta",


configfile: "defaults/config.yaml"

GENE_MASKS = config["gene_mask"]
MODES = ["basic", "stitched", "single-clade"]
ALL_GTS = config["all_genotypes"]
SINGLE_BUILD_GENOTYPES = config["single_build_genotypes"]

include: "rules/filter_and_masking.smk"




rule all: 
    input: 
        #sequences = "data/filtered/sequences.len_filtered.fasta",
        #alignment = "data/masked/alignment.len_filtered.P.fasta",
        #tree_nwk="data/P_masked_refined.tree.nwk",
        #metadata = "data/P_metadata.pruned.tsv",
        #node_data = "data/ancestral/P.json",
        #ancestral_sequences = "data/ancestral/P.fasta",
        aln_basic=       expand("results/basic/all/{gene}.json", gene=GENE_MASKS),
        aln_stitched=    expand("results/stitched/{g}/{gene}.json", g=ALL_GTS, gene=GENE_MASKS),
        aln_single_clade=expand("results/single-clade/{g}/{gene}.json", g=SINGLE_BUILD_GENOTYPES, gene=GENE_MASKS),
        stitched_collect_done = expand("results/stitched/{gene}_global/collect.done", gene=GENE_MASKS),
        stitched_tree         = expand("results/stitched/{gene}_global/tree_raw.nwk", gene=GENE_MASKS),

rule augur_tree:
    input:
        alignment = "results/{mode}/{key}/masked.{gene}.fasta",
    output:
        tree = "results/{mode}/{key}/{gene}_masked.tree.nwk",
    threads: 4
    shell:
        """
        augur tree \
          --alignment {input.alignment} \
          --method fasttree \
          --output {output.tree}
        """

rule cut_outliers:
    input:
        tree_nwk="results/{mode}/{key}/{gene}_masked.tree.nwk",
        metadata="results/{mode}/{key}/filtered.tsv",
    output:
        out_tree="results/{mode}/{key}/{gene}_masked.pruned.tree.nwk",
        metadata="results/{mode}/{key}/{gene}_metadata.pruned.tsv",
        exclude="results/{mode}/{key}/{gene}_exclude.txt",
    params:
        long_branch_threshold=config["long_branch_threshold"],
        tip_branch_threshold=config["tip_branch_threshold"],
    shell:
        r"""
        python scripts/prune_trees.py \
          --tree {input.tree_nwk} \
          --metadata-in {input.metadata} \
          --metadata-out {output.metadata} \
          --cutoff_allbranches {params.long_branch_threshold} \
          --cutoff_tips {params.tip_branch_threshold} \
          --out-tree {output.out_tree} \
          --exclude {output.exclude}

        n=$(wc -l < {output.exclude})
        echo "$n unique accessions in {output.exclude}"
        """



rule augur_refine:
    input:
        tree="results/{mode}/{key}/{gene}_masked.pruned.tree.nwk",
        alignment = "results/{mode}/{key}/masked.{gene}.fasta"
    output:
        tree="results/{mode}/{key}/{gene}_masked_refined.tree.nwk",
    threads: 4
    shell:
        """
        augur refine \
          --tree {input.tree} \
          --alignment {input.alignment} \
          --root mid_point \
          --output-tree {output.tree}
        """


# NOTE THAT THIS MAPPING INCLUDES PRE-REGIONS IN C AND S 
rule alias_translations_for_augur:
    input:
        pol="../ingest/data/nextclade/cds_pol.fasta",
        s="../ingest/data/nextclade/cds_envL.fasta",
        c="../ingest/data/nextclade/cds_pre-capsid.fasta",
    output:
        p=temp("../ingest/data/nextclade/cds_P.fasta"),
        s=temp("../ingest/data/nextclade/cds_S.fasta"),
        c=temp("../ingest/data/nextclade/cds_C.fasta")
    shell:
        r"""
        cp {input.pol} {output.p}
        cp {input.s}   {output.s}
        cp {input.c}   {output.c}
        """



rule ancestral:
    input:
        tree="results/{mode}/{key}/{gene}_masked_refined.tree.nwk",
        alignment="results/{mode}/{key}/filtered.fasta", # Using non-masked alignment for ancestral reconstruction
        annotation= config["reference"]["gff"],
        translations=expand("../ingest/data/nextclade/cds_{g}.fasta", g=config["genes"]), 
    output:
        node_data = "results/{mode}/{key}/ancestral/{gene}.json",
        sequences = "results/{mode}/{key}/ancestral/{gene}.fasta",
    params: 
        genes=" ".join(config["genes"]),
        translation_pattern="../ingest/data/nextclade/cds_%GENE.fasta",

    threads: 4
    shell:
        r"""
        augur ancestral \
          --tree {input.tree} \
          --alignment {input.alignment} \
          --annotation {input.annotation} \
          --genes {params.genes} \
          --translations {params.translation_pattern} \
          --output-node-data {output.node_data} \
          --output-sequences {output.sequences} \

        """


rule augur_export:
    wildcard_constraints:
        gene="P|S|C|X"  
    input:
        tree       ="results/{mode}/{key}/{gene}_masked_refined.tree.nwk",
        node_data = "results/{mode}/{key}/ancestral/{gene}.json",
        metadata   ="results/{mode}/{key}/{gene}_metadata.pruned.tsv",
        config     ="defaults/auspice_config.json",
    output:
        auspice_json = "results/{mode}/{key}/{gene}.json",
    threads: 1
    shell:
        """
        augur export v2 \
        --tree "{input.tree}" \
        --node-data "{input.node_data}"  \
        --metadata "{input.metadata}" \
        --metadata-id-columns accession \
        --auspice-config "{input.config}" \
        --color-by-metadata \
            genotype_genbank \
            subgenotype_genbank \
            clade_nextclade \
            genotype \
            taxon_id \
            host \
            is_lab_host \
            region \
            country \
            division \
            location \
            year \
            date \
            strain \
            isolate \
        --output "{output.auspice_json}"
        """


#______________________________________________________________________________________________________________________________________________________________________________________________



rule collect_trees_for_stitching:
    input:
        trees=lambda wc: expand(
            "results/stitched/{g}/{gene}_masked_refined.tree.nwk",
            g=ALL_GTS, gene=[wc.gene]
        ),
        alns=lambda wc: expand(
            "results/stitched/{g}/masked.{gene}.fasta",
            g=ALL_GTS, gene=[wc.gene]
        ),
    output:
        trees_dir=directory("results/stitched/{gene}_global/trees"),
        aln_dir=directory("results/stitched/{gene}_global/aln"),
        touch="results/stitched/{gene}_global/collect.done",
    params:
        g_list=" ".join(ALL_GTS)
    shell:
        r"""
        mkdir -p {output.trees_dir} {output.aln_dir}

        for g in {params.g_list}; do
            cp "results/stitched/$g/{wildcards.gene}_masked_refined.tree.nwk" "{output.trees_dir}/$g.nwk"
            cp "results/stitched/$g/masked.{wildcards.gene}.fasta"            "{output.aln_dir}/$g.fasta"
        done

        touch {output.touch}
        """


rule group_trees:
    input:
        done="results/stitched/{gene}_global/collect.done"
    output:
        stitched_tree="results/stitched/{gene}_global/tree_raw.nwk"
    params:
        trees="results/stitched/{gene}_global/trees",
        aln="results/stitched/{gene}_global/aln"
    shell:
        r"""
        python3 scripts/make_global_tree.py \
          --tree-dir {params.trees} \
          --alignment-dir {params.aln} \
          --output {output.stitched_tree}
        """
