
#    Expcted inputs from ingest:
#        sequences="../ingest/results/sequences.fasta",
#        metadata="../ingest/results/metadata.tsv",
#        alignment="../ingest/results/aligned.fasta",
#______________________________________________________________________________________________________________________________________________________________________________________________


#if config file not defined else snakemake --configfile
configfile: "defaults/config.yaml"


#______________________________________________________________________________________________________________________________________________________________________________________________

GENE_MASKS = config["gene_mask"]
MODES = ["basic", "stitched", "single-clade"]
ALL_GTS = config["all_genotypes"]
SINGLE_BUILD_GENOTYPES = config["single_build_genotypes"]
STITCHED_DIR = "results/stitched/{gene}_global"
ANCESTRAL_GENES = config["ancestral_genes"]["dev"] if config.get("dev", False) else config["ancestral_genes"]["prod"]
#______________________________________________________________________________________________________________________________________________________________________________________________


# Single genotype trees and basic non-stitched tree only for development mode
single_clade_targets = (
    expand("auspice_datasets/{gene}_masked/clade_{key}.json", gene=GENE_MASKS, key=SINGLE_BUILD_GENOTYPES)
    if config.get("dev", False)
    else []
)

full_tree_target = (
    expand("auspice_datasets/{gene}_masked/full-tree.json", gene=GENE_MASKS)
    if config.get("dev", False)
    else []
)

#______________________________________________________________________________________________________________________________________________________________________________________________

rule all: 
    input: 
        main_clades   = expand("auspice_datasets/{gene}_masked/main-clades.json", gene=GENE_MASKS),
        single_clades = single_clade_targets,
        full_tree     = full_tree_target


#______________________________________________________________________________________________________________________________________________________________________________________________
# Length filtering, other filter steps that specifcy the different builds, and gene masking
include: "rules/filter_and_masking.smk"
# Augur tree, pruning problematic clades, refinement and ancestral reconstruction
include: "rules/generating_tree.smk"
# For "stitched" builds only: Collecting, and stitching single genotype trees, again refining and ancestral reconstruction
include: "rules/stitching_workflow.smk"
# Assignment of clades and subclades (also for internal nodes)
include: "rules/clade_assignment.smk"
# Augur export and creating auspice datasets 
include: "rules/export_and_auspice_view.smk"