

# Used to re-circularise genomes. This should be the same as the reference in the nextclade dataset!
reference_accession: "NC_003977"


# Path to the nextclade dataset, which will be used to align all sequences
nextclade_dataset: "nextclade_datasets/references/NC_003977/versions/2023-08-22"

nextclade_binary: "bin/nextclade"