length_filtering: true
min_length: 3000
max_length: 3400




reference:
  id: NC_003977
  genbank: ../ingest/defaults/NC_003977.gb

genomic_regions: defaults/genomic_regions_genes.txt
#genomic_regions: defaults/genomic_regions_breakpoints.txt



# Current breakpoints based on https://journals.asm.org/doi/10.1128/jvi.79.24.15467-15476.2005, published in 2005
breakpoints:
  old_ref: X02763.1
  list: [750, 900, 1600, 1950, 2500, 2650, 2750]
  buffer: 0  # Controls for the amount of variability around breakpoints when extracting segments 
  out: defaults/genomic_regions_breakpoints_2005.txt
  map_out: defaults/X02763_to_NC_003977_map.tsv

  







