length_filtering: true
min_length: 3000
max_length: 3400




reference:
  id: NC_003977
  genbank: ../ingest/defaults/NC_003977.gb

genomic_regions: defaults/genomic_regions_genes.txt
#genomic_regions: defaults/genomic_regions_breakpoints_2005.txt



# Current breakpoints based on https://journals.asm.org/doi/10.1128/jvi.79.24.15467-15476.2005, published in 2005
breakpoints:
  old_ref: X02763.1
  list: [1, 750, 900, 1600, 1950, 2500, 2650, 2750] # Make sure to include 0 if there is a segment starting at the beginning of the genome
  buffer: 25  # Controls for the amount of variability around breakpoints when extracting segments 
  out: defaults/genomic_regions_breakpoints_2005.txt
  map_out: defaults/X02763_to_NC_003977_map.tsv



min_coverage_per_region: 0.8  # Minimum fraction of region that must be covered in a sequence for it to be retained in that segment's alignment

metadata_keep_cols:
  - name
  - accession
  - accession_version
  - strain
  - isolate
  - date
  - year
  - region
  - country
  - division
  - location
  - length
  - host
  - is_lab_host
  - date_released
  - date_updated
  - authors
  - full_authors
  - institution
  - url
  - genotype
  - taxon_id
  - genotype_genbank
  - subgenotype_genbank
  - circularise
  - circularise_shift_bp
  - clade_nextclade



# Path to the nextclade dataset, which will be used to align all sequences
nextclade_dataset: "../nextclade_datasets/references/NC_003977/versions/2023-08-22"




n_subsamples_pairwise_distance_comparison: 10000

# all branches with length higher than this threshold will be pruned from the tree
long_branch_threshold: 1 
tip_branch_threshold: 0.1



treeknit:
  n_subset: 10000
  treeknit_seed: 1


