configfile: "defaults/config.yaml"


#    Expcted inputs from ingest:
#        sequences="../ingest/results/sequences.fasta",
#        metadata="../ingest/results/metadata.tsv",
#        alignment="../ingest/results/aligned.fasta",


def region_names(path):
    names = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            names.append(line.split()[0])  # first column = name
    return names

def make_tag(regions):
    if set(regions) == {"C","P","S","X"}:
        return "genes"
    if set(regions) == {"segment1","segment2","segment3","segment4","segment5","segment6","segment7","segment8"}:
        return "segments1-8"
    return "_".join(regions)


REGION_NAMES = region_names(config["genomic_regions"])
REGION_TAG = "_".join(REGION_NAMES)
OUTDIR = "data/regions"
GENES = {"X", "P", "S", "C"}
PAIRS = [(REGION_NAMES[i], REGION_NAMES[j])
         for i in range(len(REGION_NAMES))
         for j in range(i+1, len(REGION_NAMES))]


rule all:
    input:
        fasta         = expand(f"{OUTDIR}" + "/{name}/{name}_sub-alignment.fasta", name=REGION_NAMES),
        gb            = expand(f"{OUTDIR}" + "/{name}/{name}.gb", name=REGION_NAMES),
        tree_json     = expand(f"{OUTDIR}" + "/{name}/{name}.json", name=REGION_NAMES),
        node_data     = expand(f"{OUTDIR}/{{name}}/{{name}}.ancestral.json", name=REGION_NAMES),
        joint_exclude ="defaults/exclude.txt",



rule copy:
    input:
        sequences = "../ingest/results/sequences.fasta",
        metadata  = "../ingest/results/metadata.tsv",
        alignment = "../ingest/results/aligned.fasta",
    output:
        sequences = "data/sequences.fasta",
        metadata  = "data/metadata.tsv",
        alignment = "data/alignment.fasta",
    shell:
        """
        mkdir -p data
        cp {input.sequences} {output.sequences}
        cp {input.metadata} {output.metadata}
        cp {input.alignment} {output.alignment}
        """

rule length_filter:
    input:
        sequences = "data/sequences.fasta",
        metadata  = "data/metadata.tsv",
        alignment = "data/alignment.fasta",
    output:
        sequences = "data/filtered/sequences.len_filtered.fasta",
        alignment = "data/filtered/alignment.len_filtered.fasta",
        metadata  = "data/filtered/metadata.len_filtered.tsv",
    params:
        min_length = config["min_length"],
        max_length =config["max_length"],
        length_filtering=config["length_filtering"],
    shell:
        r"""
        mkdir -p data
        kept_ids="$(mktemp)"

        if [ "{params.length_filtering}" = "true" ] || [ "{params.length_filtering}" = "True" ] || [ "{params.length_filtering}" = "1" ]; then
            seqkit seq -g -m={params.min_length} -M={params.max_length} {input.sequences} > {output.sequences}

            seqkit seq -n {output.sequences} > "$kept_ids"

            seqkit grep -f "$kept_ids" {input.alignment} > {output.alignment}

            awk 'NR==FNR {{a[$1]=1; next}} FNR==1 || ($1 in a)' "$kept_ids" {input.metadata} > {output.metadata}
        else
            cp {input.sequences} {output.sequences}
            cp {input.alignment} {output.alignment}
            cp {input.metadata} {output.metadata}
        fi

        rm -f "$kept_ids"
        """


# Writes segments file based on gene annotations in reference GenBank
rule specify_genomic_regions_genes:
    input:
        ref_gb=config["reference"]["genbank"],
        script="scripts/specify_genomic_regions_genes.py",
    output:
        regions="defaults/genomic_regions_genes.txt",
    shell:
        r"""
        python {input.script} {input.ref_gb} {output.regions} 
        """

# Writes segments file based on previously identified breakpoints
rule specify_genomic_regions_breakpoints:
    input:
        ref_gb=config["reference"]["genbank"],
        script="scripts/specify_genomic_regions_breakpoints.py",
    output:
        regions=config["breakpoints"]["out"],
        mapping=config["breakpoints"]["map_out"],
    params:
        old_ref=config["breakpoints"]["old_ref"],
        bps=lambda wc: " ".join(map(str, config["breakpoints"]["list"])),
        buffer=int(config["breakpoints"].get("buffer", 0)),
    shell:
        r"""
        python {input.script} \
          --ref-gb {input.ref_gb} \
          --old-ref {params.old_ref} \
          --breakpoints {params.bps} \
          --buffer {params.buffer} \
          --map-out {output.mapping} \
          --out {output.regions}
        """


# To Do: have this segment the tsv metadata as well, including calculating new quality metrics
# To Do: make this work for non complete sequences, i.e. additional filtering for each region if region not sufficiently covered
rule extract_genomic_regions:
    input:
        alignment="data/filtered/alignment.len_filtered.fasta",
        regions=config["genomic_regions"],
        ref_gb=config["reference"]["genbank"],
        script="scripts/extract_regions.py",
        metadata="data/filtered/metadata.len_filtered.tsv",

    output:
        fasta=expand(f"{OUTDIR}" + "/{name}/{name}_sub-alignment.fasta", name=REGION_NAMES),
        gb=expand(f"{OUTDIR}" + "/{name}/{name}.gb", name=REGION_NAMES),
        metadata=expand(f"{OUTDIR}" + "/{name}/{name}_metadata.tsv", name=REGION_NAMES),
    params:
        ref_id=config["reference"]["id"],
        outdir=OUTDIR,
        min_cov=config["min_coverage_per_region"],
        metadata_cols=" ".join(config["metadata_keep_cols"])

    shell:
        r"""
        mkdir -p {params.outdir}
        python scripts/extract_regions.py \
            {input.alignment} \
            {input.regions} \
            {params.ref_id} \
            {input.ref_gb} \
            {params.outdir} \
            --min-cov {params.min_cov} \
            --metadata {input.metadata} \
            --keep-cols {params.metadata_cols}
        """

rule augur_tree:
    input:
        alignment = f"{OUTDIR}" + "/{name}/{name}_sub-alignment.fasta",
    output:
        tree = f"{OUTDIR}" + "/{name}/{name}.tree.nwk",
    threads: 4
    shell:
        """
        augur tree \
          --alignment {input.alignment} \
          --method fasttree \
          --output {output.tree}
        """
        


rule cut_outliers:
    input:
        tree_nwk = f"{OUTDIR}/{{name}}/{{name}}.tree.nwk",
        metadata = f"{OUTDIR}/{{name}}/{{name}}_metadata.tsv",
    output:
        out_tree = f"{OUTDIR}/{{name}}/{{name}}.pruned.tree.nwk",
        metadata = f"{OUTDIR}/{{name}}/{{name}}_metadata.pruned.tsv",
        exclude = f"defaults/{{name}}_excluded_accessions.txt",
    params:
        long_branch_threshold = config["long_branch_threshold"],
        tip_branch_threshold = config["tip_branch_threshold"],
    shell:
        """
        python scripts/prune_trees.py \
            --tree {input.tree_nwk} \
            --metadata-in {input.metadata} \
            --metadata-out {output.metadata} \
            --cutoff_allbranches {params.long_branch_threshold} \
            --cutoff_tips {params.tip_branch_threshold} \
            --out-tree {output.out_tree} \
            --exclude {output.exclude}
        """


rule joint_exclude_file:
    input:
        excludes=expand(f"defaults/{{name}}_excluded_accessions.txt", name=REGION_NAMES),
    output:
        joint_exclude="defaults/exclude.txt",
    shell:
        """
        cat defaults/*_excluded_accessions.txt \
        | tr -s '[:space:]' '\n' \
        | awk 'NF' \
        | sort -u \
        > {output.joint_exclude}

        n=$(wc -l < {output.joint_exclude})
        echo "$n unique accessions written to {output.joint_exclude}"
        """


rule augur_refine:
    input:
        tree      = f"{OUTDIR}" + "/{name}/{name}.pruned.tree.nwk",
        alignment = f"{OUTDIR}" + "/{name}/{name}_sub-alignment.fasta",
    output:
        tree      = f"{OUTDIR}" + "/{name}/{name}.refined.tree.nwk",
    threads: 4
    shell:
        """
        augur refine \
          --tree {input.tree} \
          --alignment {input.alignment} \
          --root mid_point \
          --output-tree {output.tree}
        """



rule ancestral:
    input:
        tree = f"{OUTDIR}/{{name}}/{{name}}.refined.tree.nwk",
        alignment = f"{OUTDIR}/{{name}}/{{name}}_sub-alignment.fasta",
    output:
        node_data = f"{OUTDIR}/{{name}}/{{name}}.ancestral.json",
        sequences = f"{OUTDIR}/{{name}}/{{name}}.ancestral_sequences.fasta",
    threads: 4
    shell:
        r"""
        augur ancestral \
          --tree {input.tree} \
          --alignment {input.alignment} \
          --output-node-data {output.node_data} \
          --output-sequences {output.sequences} \
        """

# THIS DOES NOT RUN SINCE SEGMENTS ONLY PARTIALLY OVERLAP WITH CDS AND AUGUR TRANSLATE CANNOT HANDLE THAT
#rule translate_ancestral:
#    input:
#        tree      = f"{OUTDIR}/{{name}}/{{name}}.refined.tree.nwk",
#        ancestral = f"{OUTDIR}/{{name}}/{{name}}.ancestral.json",
#        ref_gb    = f"{OUTDIR}/{{name}}/{{name}}.gb",
#    output:
#       aa        = f"{OUTDIR}/{{name}}/{{name}}.aa-mutations.json",
#    run:
#        shell(r"""
#        augur translate \
#          --tree {input.tree} \
#          --ancestral-sequences {input.ancestral} \
#          --reference-sequence {input.ref_gb} \
#          --output-node-data {output.aa}
#        """)


rule augur_export:
    input:
        tree         = f"{OUTDIR}/{{name}}/{{name}}.refined.tree.nwk",
        node_data    = f"{OUTDIR}/{{name}}/{{name}}.ancestral.json",
        metadata     = f"{OUTDIR}" + "/{name}/{name}_metadata.pruned.tsv",
        config       = "defaults/auspice_config.json",
    output:
        auspice_json = f"{OUTDIR}" + "/{name}/{name}.json",
    threads: 1
    shell:
        """
        augur export v2 \
        --tree "{input.tree}" \
        --node-data "{input.node_data}"  \
        --metadata "{input.metadata}" \
        --metadata-id-columns accession \
        --auspice-config {input.config}\
        --color-by-metadata \
            genotype_genbank \
            subgenotype_genbank \
            clade_nextclade \
            genotype \
            taxon_id \
            host \
            is_lab_host \
            region \
            country \
            division \
            location \
            year \
            date \
            strain \
            isolate \
        --output "{output.auspice_json}"

        """



# rules to compare differnt region trees to inform recombination via different metrics (partially have to be called individually)
include: "rules/tree_comparisons.smk"
